import { AuthProvider } from "@/contexts/AuthContext";

import "@/styles/globals.css";

import { type FC } from "react";

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Blue Log",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = (props) => {
  return (
    <html lang="ja">
      <body className="">
        <AuthProvider>{props.children}</AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
