import { AuthProvider } from "@/contexts/AuthContext";

import "@/styles/globals.css";

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Blue Log",
  description: "Generated by create next app",
};

const RootLayout = (props: RootLayoutProps) => {
  return (
    <html lang="ja">
      <body className="">
        <AuthProvider>{props.children}</AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
